trigger:
- main  # Change this to your branch name

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'Azure-Managed-Services-main/Azure Monitor/AT/VMAlerts/VMAlertsSingle/Disk-Data Disk IOPS Consumed Percentage.ps1'  # Path to your PowerShell script
    arguments: '-YourArgument value'      # Optional: any arguments you want to pass
    failOnStderr: true                     # Optional: fail the task if there's an error
  displayName: 'Run PowerShell Script'
